apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lk25oc13r-java-quarkus
  janus-idp.io/tekton: lk25oc13r-java-quarkus
  backstage.io/kubernetes-id: lk25oc13r-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lk25oc13r-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
